[project]
name = "retro"
languages = ["CXX"]

[conditions]
x86_64 = "CMAKE_SYSTEM_PROCESSOR MATCHES \"(amd64)|(AMD64)|(x86_64)\""

[subdir.zydis]
[subdir.linux-pe]
[subdir.scripts]

[target.libretro]
type = "static"
link-libraries = ["Zydis", "linux-pe"]
include-directories = ["libretro/include"]
compile-features = ["cxx_std_23"]
sources = [
    "libretro/src/**.cpp",
    "libretro/src/**.hpp",
    "libretro/src/**.hxx",
    "libretro/include/**.hpp",
    "libretro/include/**.hxx",
]

[target.retro]
type = "executable"
link-libraries = ["libretro"]
sources = ["libretro/src/main.cpp"]

[[install]]
targets = ["retro"]
destination = "bin"
