Includes = [
	"<retro/targets.hxx>",
	"<string>",
]

type_kind = [
	"memory",
	"scalar-int",
	"scalar-fp",
	"vector-int",
	"vector-fp",
]

# Generate SIMD types.
#
Script = """
SIMD_WIDTHS = [128, 256, 512]

for l in SIMD_WIDTHS:
	# Generate int types.
	for k in [64, 32, 16, 8]:
		ty = "i" + str(k)
		lane_width = l // k
		vty = "{0}x{1}".format(ty, lane_width)
		desc = {
			"kind":        "@type_kind.vector-int",
			"underlying":  "@type." + ty,
			"lane_width":  lane_width,
			"bit_size":    l,
			"VisitorArgs": [vty]
		}
		data["type"][vty] = desc

	# Generate float types.
	for k in [64, 32]:
		ty = "f" + str(k)
		lane_width = l // k
		vty = "{0}x{1}".format(ty, lane_width)
		desc = {
			"kind":        "@type_kind.vector-fp",
			"underlying":  "@type." + ty,
			"lane_width":  lane_width,
			"bit_size":    l,
			"VisitorArgs": [vty]
		}
		data["type"][vty] = desc
"""

# Pseudo aka "none".
#
[type.pack]
VisitorArgs = ["retro::ir::value_pack_t"]
[type.reg]
VisitorArgs = ["retro::reg"]
[type.op]
VisitorArgs = ["retro::ir::op"]
[type.intrinsic]
VisitorArgs = ["retro::ir::intrinsic"]
[type.label]
VisitorArgs = ["basic_block*"]
[type.str]
VisitorArgs = ["std::string_view"]

# Integer types.
#
[type.i1]
kind     =    "@type_kind.scalar-int"
bit_size =    1
VisitorArgs = ["bool"]
[type.i8]
kind     =    "@type_kind.scalar-int"
bit_size =    8
VisitorArgs = ["i8"]
[type.i16]
kind     =    "@type_kind.scalar-int"
bit_size =    16
VisitorArgs = ["i16"]
[type.i32]
kind     =    "@type_kind.scalar-int"
bit_size =    32
VisitorArgs = ["i32"]
[type.i64]
kind     =    "@type_kind.scalar-int"
bit_size =    64
VisitorArgs = ["i64"]
[type.i128]
kind     =    "@type_kind.scalar-int"
bit_size =    128
VisitorArgs = ["i128"]

# Floating point types.
#
[type.f32]
kind     =    "@type_kind.scalar-fp"
bit_size =    32
VisitorArgs = ["f32"]
[type.f64]
kind     =    "@type_kind.scalar-fp"
bit_size =    64
VisitorArgs = ["f64"]

# Pointer types.
#
[type.pointer]
kind     =    "@type_kind.memory"
bit_size =    64
VisitorArgs = ["retro::ir::pointer"]
[type.segment]
kind     =    "@type_kind.memory"
bit_size =    32
VisitorArgs = ["retro::ir::segment"]