Includes = [
	"<retro/ir/builtin_types.hxx>"
]
Forwards = [
	"type"
]

op-kind = [
	"unary-signed",
	"unary-unsigned",
	"unary-bitwise",
	"unary-float",
	"binary-signed",
	"binary-unsigned",
	"binary-bitwise",
	"binary-float",
	"op-signed",
	"op-unsigned",
]

# Unary operations
#
[op.neg]
symbol = "-"
kind   = "@op-kind.unary-signed"
inverse = "@op.neg"
[op.abs]
symbol = "abs"
kind   = "@op-kind.unary-signed"
[op.bit_lsb]
symbol = "lsb"
kind   = "@op-kind.unary-bitwise"
[op.bit_msb]
symbol = "msb"
kind   = "@op-kind.unary-bitwise"
[op.bit_popcnt]
symbol = "popcnt"
kind   = "@op-kind.unary-bitwise"
[op.bit_swap]
symbol = "bswap"
kind   = "@op-kind.unary-bitwise"
[op.bit_not]
symbol = "~"
kind   = "@op-kind.unary-bitwise"
inverse = "@op.bit_not"
[op.ceil]
symbol = "ceil"
kind   = "@op-kind.unary-float"
[op.floor]
symbol = "floor"
kind   = "@op-kind.unary-float"
[op.trunc]
symbol = "trunc"
kind   = "@op-kind.unary-float"
[op.round]
symbol = "round"
kind   = "@op-kind.unary-float"

# Binary operations
#
[op.add]
symbol = "+"
kind   = "@op-kind.binary-signed"
commutative = true
[op.sub]
symbol = "-"
kind   = "@op-kind.binary-signed"
[op.mul]
symbol = "*"
kind   = "@op-kind.binary-signed"
swap_sign = "@op.umul"
commutative = true
[op.umul]
symbol = "*"
kind   = "@op-kind.binary-unsigned"
swap_sign = "@op.mul"
commutative = true
[op.div]
symbol = "/"
kind   = "@op-kind.binary-signed"
swap_sign = "@op.udiv"
[op.udiv]
symbol = "/"
kind   = "@op-kind.binary-unsigned"
swap_sign = "@op.div"
[op.rem]
symbol = "%"
kind   = "@op-kind.binary-signed"
swap_sign = "@op.urem"
[op.urem]
symbol = "%"
kind   = "@op-kind.binary-unsigned"
swap_sign = "@op.rem"
[op.bit_or]
symbol = "|"
kind   = "@op-kind.binary-bitwise"
commutative = true
[op.bit_and]
symbol = "&"
kind   = "@op-kind.binary-bitwise"
commutative = true
[op.bit_xor]
symbol = "^"
kind   = "@op-kind.binary-bitwise"
inverse = "@op.bit_xor"
commutative = true
[op.bit_shl]
symbol = "<<"
kind   = "@op-kind.binary-bitwise"
[op.bit_shr]
symbol = ">>"
kind   = "@op-kind.binary-bitwise"
swap_sign = "@op.bit_sar"
[op.bit_sar]
symbol = ">>"
kind   = "@op-kind.binary-bitwise"
swap_sign = "@op.bit_shr"
[op.bit_rol]
symbol = "rotl"
kind   = "@op-kind.binary-bitwise"
inverse = "@op.bit_ror"
[op.bit_ror]
symbol = "rotr"
kind   = "@op-kind.binary-bitwise"
inverse = "@op.bit_rol"
[op.max]
symbol = "max"
kind   = "@op-kind.binary-signed"
swap_sign = "@op.umax"
commutative = true
[op.umax]
symbol = "umax"
kind   = "@op-kind.binary-unsigned"
swap_sign = "@op.max"
commutative = true
[op.min]
symbol = "min"
kind   = "@op-kind.binary-signed"
swap_sign = "@op.umin"
commutative = true
[op.umin]
symbol = "umin"
kind   = "@op-kind.binary-unsigned"
swap_sign = "@op.min"
commutative = true

# Comperators
#
[op.gt]
symbol = ">"
kind   = "@op-kind.op-signed"
inverse = "@op.le"
swap_sign  = "@op.ugt"
[op.ugt]
symbol = ">"
kind   = "@op-kind.op-unsigned"
inverse = "@op.ule"
swap_sign  = "@op.gt"
[op.le]
symbol = "<="
kind   = "@op-kind.op-signed"
inverse = "@op.gt"
swap_sign = "@op.ule"
[op.ule]
symbol = "<="
kind   = "@op-kind.op-unsigned"
inverse = "@op.ugt"
swap_sign = "@op.le"
[op.ge]
symbol = ">="
kind   = "@op-kind.op-signed"
inverse = "@op.lt"
swap_sign  = "@op.uge"
[op.uge]
symbol = ">="
kind   = "@op-kind.op-unsigned"
inverse = "@op.ult"
swap_sign  = "@op.ge"
[op.lt]
symbol = "<"
kind   = "@op-kind.op-signed"
inverse = "@op.ge"
swap_sign = "@op.ult"
[op.ult]
symbol = "<"
kind   = "@op-kind.op-unsigned"
inverse = "@op.uge"
swap_sign = "@op.lt"
[op.eq]
symbol = "=="
kind   = "@op-kind.op-signed"
inverse = "@op.ne"
commutative = true
[op.ne]
symbol = "!="
kind   = "@op-kind.op-signed"
inverse = "@op.eq"
commutative = true

# Memory intrinsics.
#
[intrinsic.stack-alloc]
symbol = "alloca"
args =   ["@type.i32"]
ret =    "@type.pointer"
[intrinsic.malloc]
args =   ["@type.i64"]
ret =    "@type.pointer"
[intrinsic.realloc]
args =   ["@type.pointer", "@type.i64"]
ret =    "@type.pointer"
[intrinsic.free]
args =   ["@type.pointer"]
[intrinsic.sfence]
args =   []
[intrinsic.lfence]
args =   []
[intrinsic.mfence]
args =   []

# String intrinsics.
#
[intrinsic.memcpy]
args =   ["@type.pointer", "@type.pointer", "@type.i64"]
ret =    "@type.pointer"
[intrinsic.memmove]
args =   ["@type.pointer", "@type.pointer", "@type.i64"]
ret =    "@type.pointer"
[intrinsic.memcmp]
args =   ["@type.pointer", "@type.pointer", "@type.i64"]
ret =    "@type.i32"
[intrinsic.memset]
args =   ["@type.pointer", "@type.i32", "@type.i64"]
ret =    "@type.pointer"
[intrinsic.memchr]
args =   ["@type.pointer", "@type.i32", "@type.i64"]
ret =    "@type.pointer"
[intrinsic.strcpy]
args =   ["@type.pointer", "@type.pointer"]
ret =    "@type.pointer"
[intrinsic.strcmp]
args =   ["@type.pointer", "@type.pointer"]
ret =    "@type.i32"
[intrinsic.strchr]
args =   ["@type.pointer", "@type.i32"]
ret =    "@type.pointer"
[intrinsic.strstr]
args =   ["@type.pointer", "@type.pointer"]
ret =    "@type.pointer"

# FP intrinsics.
#
[intrinsic.sin]
args =   ["@type.f64"]
ret =    "@type.f64"
[intrinsic.cos]
args =   ["@type.f64"]
ret =    "@type.f64"
[intrinsic.tan]
args =   ["@type.f64"]
ret =    "@type.f64"
[intrinsic.asin]
args =   ["@type.f64"]
ret =    "@type.f64"
[intrinsic.acos]
args =   ["@type.f64"]
ret =    "@type.f64"
[intrinsic.atan]
args =   ["@type.f64"]
ret =    "@type.f64"
[intrinsic.atan2]
args =   ["@type.f64", "@type.f64"]
ret =    "@type.f64"
[intrinsic.exp]
args =   ["@type.f64"]
ret =    "@type.f64"
[intrinsic.pow]
args =   ["@type.f64", "@type.f64"]
ret =    "@type.f64"
[intrinsic.sqrt]
args =   ["@type.f64"]
ret =    "@type.f64"
[intrinsic.log]
args =   ["@type.f64"]
ret =    "@type.f64"
[intrinsic.copysign]
args =   ["@type.f64", "@type.f64"]
ret =    "@type.f64"

# Low level intrinsics.
#
[intrinsic.retaddr]
symbol = "_ReturnAddress"
args =   []
ret =    "@type.pointer"
[intrinsic.addr-retaddr]
symbol = "_AddressOfReturnAddress"
args =   []
ret =    "@type.pointer"