# Identity constants.
#
[[replace]]
src = "A+0"
dst = "A"
[[replace]]
src = "A-0"
dst = "A"
[[replace]]
src = "A|A"
dst = "A"
[[replace]]
src = "A|0"
dst = "A"
[[replace]]
src = "A&A"
dst = "A"
[[replace]]
src = "A^0"
dst = "A"
[[replace]]
src = "A&[-1]"
dst = "A"
[[replace]]
src = "A*1"
dst = "A"
[[replace]]
src = "A/1"
dst = "A"
[[replace]]
src = "Au/1"
dst = "A"
[[replace]]
src = "rotl(A,0)"
dst = "A"
[[replace]]
src = "rotr(A,0)"
dst = "A"
[[replace]]
src = "A>>0"
dst = "A"
[[replace]]
src = "As>>0"
dst = "A"
[[replace]]
src = "A<<0"
dst = "A"

# Expressions with constant results.
#
[[replace]]
src = "A-A"
dst = "0"
[[replace]]
src = "A&0"
dst = "0"
[[replace]]
src = "A&(~A)"
dst = "0"
[[replace]]
src = "A^A"
dst = "0"
[[replace]]
src = "A|[-1]"
dst = "[-1]"
[[replace]]
src = "A+(~A)"
dst = "[-1]"
[[replace]]
src = "A^(~A)"
dst = "[-1]"
[[replace]]
src = "A/A"
dst = "1"
[[replace]]
src = "Au/A"
dst = "1"
[[replace]]
src = "A%A"
dst = "0"
[[replace]]
src = "Au%A"
dst = "0"
[[replace]]
src = "A*0"
dst = "0"
[[replace]]
src = "A*0"
dst = "0"