import { RegKind } from "../reg_kind";

// prettier-ignore
export enum Reg {
	None       = 0,
	Al         = 1,
	Cl         = 2,
	Dl         = 3,
	Bl         = 4,
	Ah         = 5,
	Ch         = 6,
	Dh         = 7,
	Bh         = 8,
	Spl        = 9,
	Bpl        = 10,
	Sil        = 11,
	Dil        = 12,
	R8b        = 13,
	R9b        = 14,
	R10b       = 15,
	R11b       = 16,
	R12b       = 17,
	R13b       = 18,
	R14b       = 19,
	R15b       = 20,
	Ax         = 21,
	Cx         = 22,
	Dx         = 23,
	Bx         = 24,
	Sp         = 25,
	Bp         = 26,
	Si         = 27,
	Di         = 28,
	R8w        = 29,
	R9w        = 30,
	R10w       = 31,
	R11w       = 32,
	R12w       = 33,
	R13w       = 34,
	R14w       = 35,
	R15w       = 36,
	Eax        = 37,
	Ecx        = 38,
	Edx        = 39,
	Ebx        = 40,
	Esp        = 41,
	Ebp        = 42,
	Esi        = 43,
	Edi        = 44,
	R8d        = 45,
	R9d        = 46,
	R10d       = 47,
	R11d       = 48,
	R12d       = 49,
	R13d       = 50,
	R14d       = 51,
	R15d       = 52,
	Rax        = 53,
	Rcx        = 54,
	Rdx        = 55,
	Rbx        = 56,
	Rsp        = 57,
	Rbp        = 58,
	Rsi        = 59,
	Rdi        = 60,
	R8         = 61,
	R9         = 62,
	R10        = 63,
	R11        = 64,
	R12        = 65,
	R13        = 66,
	R14        = 67,
	R15        = 68,
	St0        = 69,
	St1        = 70,
	St2        = 71,
	St3        = 72,
	St4        = 73,
	St5        = 74,
	St6        = 75,
	St7        = 76,
	Mm0        = 77,
	Mm1        = 78,
	Mm2        = 79,
	Mm3        = 80,
	Mm4        = 81,
	Mm5        = 82,
	Mm6        = 83,
	Mm7        = 84,
	X87control = 85,
	X87status  = 86,
	X87tag     = 87,
	Flags      = 88,
	Eflags     = 89,
	Rflags     = 90,
	Ip         = 91,
	Eip        = 92,
	Rip        = 93,
	Es         = 94,
	Cs         = 95,
	Ss         = 96,
	Ds         = 97,
	Fs         = 98,
	Gs         = 99,
	Cr0        = 100,
	Cr2        = 101,
	Cr3        = 102,
	Cr4        = 103,
	Cr8        = 104,
	Dr0        = 105,
	Dr1        = 106,
	Dr2        = 107,
	Dr3        = 108,
	Dr4        = 109,
	Dr5        = 110,
	Dr6        = 111,
	Dr7        = 112,
	FlagCf     = 113,
	FlagPf     = 114,
	FlagAf     = 115,
	FlagZf     = 116,
	FlagSf     = 117,
	FlagTf     = 118,
	FlagIf     = 119,
	FlagDf     = 120,
	FlagOf     = 121,
	FlagIopl   = 122,
	FlagNt     = 123,
	FlagRf     = 124,
	FlagVm     = 125,
	FlagAc     = 126,
	FlagVif    = 127,
	FlagVip    = 128,
	FlagId     = 129,
	Xmm0s      = 130,
	Xmm1s      = 131,
	Xmm2s      = 132,
	Xmm3s      = 133,
	Xmm4s      = 134,
	Xmm5s      = 135,
	Xmm6s      = 136,
	Xmm7s      = 137,
	Xmm8s      = 138,
	Xmm9s      = 139,
	Xmm10s     = 140,
	Xmm11s     = 141,
	Xmm12s     = 142,
	Xmm13s     = 143,
	Xmm14s     = 144,
	Xmm15s     = 145,
	Xmm0d      = 146,
	Xmm1d      = 147,
	Xmm2d      = 148,
	Xmm3d      = 149,
	Xmm4d      = 150,
	Xmm5d      = 151,
	Xmm6d      = 152,
	Xmm7d      = 153,
	Xmm8d      = 154,
	Xmm9d      = 155,
	Xmm10d     = 156,
	Xmm11d     = 157,
	Xmm12d     = 158,
	Xmm13d     = 159,
	Xmm14d     = 160,
	Xmm15d     = 161,
	Xmm0       = 162,
	Xmm1       = 163,
	Xmm2       = 164,
	Xmm3       = 165,
	Xmm4       = 166,
	Xmm5       = 167,
	Xmm6       = 168,
	Xmm7       = 169,
	Xmm8       = 170,
	Xmm9       = 171,
	Xmm10      = 172,
	Xmm11      = 173,
	Xmm12      = 174,
	Xmm13      = 175,
	Xmm14      = 176,
	Xmm15      = 177,
	Ymm0       = 178,
	Ymm1       = 179,
	Ymm2       = 180,
	Ymm3       = 181,
	Ymm4       = 182,
	Ymm5       = 183,
	Ymm6       = 184,
	Ymm7       = 185,
	Ymm8       = 186,
	Ymm9       = 187,
	Ymm10      = 188,
	Ymm11      = 189,
	Ymm12      = 190,
	Ymm13      = 191,
	Ymm14      = 192,
	Ymm15      = 193,
	// PSEUDO
	MAX        = 193,
	BIT_WIDTH  = 8,
}

///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//                                                      Descriptors                                                      //
///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

// prettier-ignore
export class RegDesc {
	name:   string  = "";
	parts:  Reg[]   = [];
	kind:   RegKind = RegKind.None;
	width:  number  = 0;
	offset: number  = 0;
	super:  Reg     = Reg.None;
}

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//                                                         Tables                                                         //
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

// prettier-ignore
const Reg_DescTable: RegDesc[] = [
	new RegDesc(),
	{name:"al",parts:[],kind:RegKind.Gpr8,width:8,offset:0,super:Reg.Rax},
	{name:"cl",parts:[],kind:RegKind.Gpr8,width:8,offset:0,super:Reg.Rcx},
	{name:"dl",parts:[],kind:RegKind.Gpr8,width:8,offset:0,super:Reg.Rdx},
	{name:"bl",parts:[],kind:RegKind.Gpr8,width:8,offset:0,super:Reg.Rbx},
	{name:"ah",parts:[],kind:RegKind.Gpr8,width:8,offset:8,super:Reg.Rax},
	{name:"ch",parts:[],kind:RegKind.Gpr8,width:8,offset:8,super:Reg.Rcx},
	{name:"dh",parts:[],kind:RegKind.Gpr8,width:8,offset:8,super:Reg.Rdx},
	{name:"bh",parts:[],kind:RegKind.Gpr8,width:8,offset:8,super:Reg.Rbx},
	{name:"spl",parts:[],kind:RegKind.Gpr8,width:8,offset:0,super:Reg.Rsp},
	{name:"bpl",parts:[],kind:RegKind.Gpr8,width:8,offset:0,super:Reg.Rbp},
	{name:"sil",parts:[],kind:RegKind.Gpr8,width:8,offset:0,super:Reg.Rsi},
	{name:"dil",parts:[],kind:RegKind.Gpr8,width:8,offset:0,super:Reg.Rdi},
	{name:"r8b",parts:[],kind:RegKind.Gpr8,width:8,offset:0,super:Reg.R8},
	{name:"r9b",parts:[],kind:RegKind.Gpr8,width:8,offset:0,super:Reg.R9},
	{name:"r10b",parts:[],kind:RegKind.Gpr8,width:8,offset:0,super:Reg.R10},
	{name:"r11b",parts:[],kind:RegKind.Gpr8,width:8,offset:0,super:Reg.R11},
	{name:"r12b",parts:[],kind:RegKind.Gpr8,width:8,offset:0,super:Reg.R12},
	{name:"r13b",parts:[],kind:RegKind.Gpr8,width:8,offset:0,super:Reg.R13},
	{name:"r14b",parts:[],kind:RegKind.Gpr8,width:8,offset:0,super:Reg.R14},
	{name:"r15b",parts:[],kind:RegKind.Gpr8,width:8,offset:0,super:Reg.R15},
	{name:"ax",parts:[],kind:RegKind.Gpr16,width:16,offset:0,super:Reg.Rax},
	{name:"cx",parts:[],kind:RegKind.Gpr16,width:16,offset:0,super:Reg.Rcx},
	{name:"dx",parts:[],kind:RegKind.Gpr16,width:16,offset:0,super:Reg.Rdx},
	{name:"bx",parts:[],kind:RegKind.Gpr16,width:16,offset:0,super:Reg.Rbx},
	{name:"sp",parts:[],kind:RegKind.Gpr16,width:16,offset:0,super:Reg.Rsp},
	{name:"bp",parts:[],kind:RegKind.Gpr16,width:16,offset:0,super:Reg.Rbp},
	{name:"si",parts:[],kind:RegKind.Gpr16,width:16,offset:0,super:Reg.Rsi},
	{name:"di",parts:[],kind:RegKind.Gpr16,width:16,offset:0,super:Reg.Rdi},
	{name:"r8w",parts:[],kind:RegKind.Gpr16,width:16,offset:0,super:Reg.R8},
	{name:"r9w",parts:[],kind:RegKind.Gpr16,width:16,offset:0,super:Reg.R9},
	{name:"r10w",parts:[],kind:RegKind.Gpr16,width:16,offset:0,super:Reg.R10},
	{name:"r11w",parts:[],kind:RegKind.Gpr16,width:16,offset:0,super:Reg.R11},
	{name:"r12w",parts:[],kind:RegKind.Gpr16,width:16,offset:0,super:Reg.R12},
	{name:"r13w",parts:[],kind:RegKind.Gpr16,width:16,offset:0,super:Reg.R13},
	{name:"r14w",parts:[],kind:RegKind.Gpr16,width:16,offset:0,super:Reg.R14},
	{name:"r15w",parts:[],kind:RegKind.Gpr16,width:16,offset:0,super:Reg.R15},
	{name:"eax",parts:[],kind:RegKind.Gpr32,width:32,offset:0,super:Reg.Rax},
	{name:"ecx",parts:[],kind:RegKind.Gpr32,width:32,offset:0,super:Reg.Rcx},
	{name:"edx",parts:[],kind:RegKind.Gpr32,width:32,offset:0,super:Reg.Rdx},
	{name:"ebx",parts:[],kind:RegKind.Gpr32,width:32,offset:0,super:Reg.Rbx},
	{name:"esp",parts:[],kind:RegKind.Gpr32,width:32,offset:0,super:Reg.Rsp},
	{name:"ebp",parts:[],kind:RegKind.Gpr32,width:32,offset:0,super:Reg.Rbp},
	{name:"esi",parts:[],kind:RegKind.Gpr32,width:32,offset:0,super:Reg.Rsi},
	{name:"edi",parts:[],kind:RegKind.Gpr32,width:32,offset:0,super:Reg.Rdi},
	{name:"r8d",parts:[],kind:RegKind.Gpr32,width:32,offset:0,super:Reg.R8},
	{name:"r9d",parts:[],kind:RegKind.Gpr32,width:32,offset:0,super:Reg.R9},
	{name:"r10d",parts:[],kind:RegKind.Gpr32,width:32,offset:0,super:Reg.R10},
	{name:"r11d",parts:[],kind:RegKind.Gpr32,width:32,offset:0,super:Reg.R11},
	{name:"r12d",parts:[],kind:RegKind.Gpr32,width:32,offset:0,super:Reg.R12},
	{name:"r13d",parts:[],kind:RegKind.Gpr32,width:32,offset:0,super:Reg.R13},
	{name:"r14d",parts:[],kind:RegKind.Gpr32,width:32,offset:0,super:Reg.R14},
	{name:"r15d",parts:[],kind:RegKind.Gpr32,width:32,offset:0,super:Reg.R15},
	{name:"rax",parts:[Reg.Al,Reg.Rax,Reg.Ah,Reg.Ax,Reg.Eax],kind:RegKind.Gpr64,width:64,offset:0,super:Reg.None},
	{name:"rcx",parts:[Reg.Cl,Reg.Rcx,Reg.Ch,Reg.Cx,Reg.Ecx],kind:RegKind.Gpr64,width:64,offset:0,super:Reg.None},
	{name:"rdx",parts:[Reg.Dl,Reg.Rdx,Reg.Dh,Reg.Dx,Reg.Edx],kind:RegKind.Gpr64,width:64,offset:0,super:Reg.None},
	{name:"rbx",parts:[Reg.Bl,Reg.Rbx,Reg.Bh,Reg.Bx,Reg.Ebx],kind:RegKind.Gpr64,width:64,offset:0,super:Reg.None},
	{name:"rsp",parts:[Reg.Spl,Reg.Rsp,Reg.Sp,Reg.Esp],kind:RegKind.Gpr64,width:64,offset:0,super:Reg.None},
	{name:"rbp",parts:[Reg.Bpl,Reg.Rbp,Reg.Bp,Reg.Ebp],kind:RegKind.Gpr64,width:64,offset:0,super:Reg.None},
	{name:"rsi",parts:[Reg.Sil,Reg.Rsi,Reg.Si,Reg.Esi],kind:RegKind.Gpr64,width:64,offset:0,super:Reg.None},
	{name:"rdi",parts:[Reg.Dil,Reg.Rdi,Reg.Di,Reg.Edi],kind:RegKind.Gpr64,width:64,offset:0,super:Reg.None},
	{name:"r8",parts:[Reg.R8b,Reg.R8,Reg.R8w,Reg.R8d],kind:RegKind.Gpr64,width:64,offset:0,super:Reg.None},
	{name:"r9",parts:[Reg.R9b,Reg.R9,Reg.R9w,Reg.R9d],kind:RegKind.Gpr64,width:64,offset:0,super:Reg.None},
	{name:"r10",parts:[Reg.R10b,Reg.R10,Reg.R10w,Reg.R10d],kind:RegKind.Gpr64,width:64,offset:0,super:Reg.None},
	{name:"r11",parts:[Reg.R11b,Reg.R11,Reg.R11w,Reg.R11d],kind:RegKind.Gpr64,width:64,offset:0,super:Reg.None},
	{name:"r12",parts:[Reg.R12b,Reg.R12,Reg.R12w,Reg.R12d],kind:RegKind.Gpr64,width:64,offset:0,super:Reg.None},
	{name:"r13",parts:[Reg.R13b,Reg.R13,Reg.R13w,Reg.R13d],kind:RegKind.Gpr64,width:64,offset:0,super:Reg.None},
	{name:"r14",parts:[Reg.R14b,Reg.R14,Reg.R14w,Reg.R14d],kind:RegKind.Gpr64,width:64,offset:0,super:Reg.None},
	{name:"r15",parts:[Reg.R15b,Reg.R15,Reg.R15w,Reg.R15d],kind:RegKind.Gpr64,width:64,offset:0,super:Reg.None},
	{name:"st0",parts:[Reg.Mm0,Reg.St0],kind:RegKind.Fp80,width:80,offset:0,super:Reg.None},
	{name:"st1",parts:[Reg.Mm1,Reg.St1],kind:RegKind.Fp80,width:80,offset:0,super:Reg.None},
	{name:"st2",parts:[Reg.Mm2,Reg.St2],kind:RegKind.Fp80,width:80,offset:0,super:Reg.None},
	{name:"st3",parts:[Reg.Mm3,Reg.St3],kind:RegKind.Fp80,width:80,offset:0,super:Reg.None},
	{name:"st4",parts:[Reg.Mm4,Reg.St4],kind:RegKind.Fp80,width:80,offset:0,super:Reg.None},
	{name:"st5",parts:[Reg.Mm5,Reg.St5],kind:RegKind.Fp80,width:80,offset:0,super:Reg.None},
	{name:"st6",parts:[Reg.Mm6,Reg.St6],kind:RegKind.Fp80,width:80,offset:0,super:Reg.None},
	{name:"st7",parts:[Reg.Mm7,Reg.St7],kind:RegKind.Fp80,width:80,offset:0,super:Reg.None},
	{name:"mm0",parts:[],kind:RegKind.Simd64,width:64,offset:0,super:Reg.St0},
	{name:"mm1",parts:[],kind:RegKind.Simd64,width:64,offset:0,super:Reg.St1},
	{name:"mm2",parts:[],kind:RegKind.Simd64,width:64,offset:0,super:Reg.St2},
	{name:"mm3",parts:[],kind:RegKind.Simd64,width:64,offset:0,super:Reg.St3},
	{name:"mm4",parts:[],kind:RegKind.Simd64,width:64,offset:0,super:Reg.St4},
	{name:"mm5",parts:[],kind:RegKind.Simd64,width:64,offset:0,super:Reg.St5},
	{name:"mm6",parts:[],kind:RegKind.Simd64,width:64,offset:0,super:Reg.St6},
	{name:"mm7",parts:[],kind:RegKind.Simd64,width:64,offset:0,super:Reg.St7},
	{name:"x87control",parts:[],kind:RegKind.Control,width:16,offset:0,super:Reg.None},
	{name:"x87status",parts:[],kind:RegKind.Control,width:16,offset:0,super:Reg.None},
	{name:"x87tag",parts:[],kind:RegKind.Control,width:16,offset:0,super:Reg.None},
	{name:"flags",parts:[],kind:RegKind.Control,width:16,offset:0,super:Reg.Rflags},
	{name:"eflags",parts:[],kind:RegKind.Control,width:32,offset:0,super:Reg.Rflags},
	{name:"rflags",parts:[Reg.Flags,Reg.Rflags,Reg.Eflags,Reg.FlagCf,Reg.FlagPf,Reg.FlagAf,Reg.FlagZf,Reg.FlagSf,Reg.FlagTf,Reg.FlagIf,Reg.FlagDf,Reg.FlagOf,Reg.FlagIopl,Reg.FlagNt,Reg.FlagRf,Reg.FlagVm,Reg.FlagAc,Reg.FlagVif,Reg.FlagVip,Reg.FlagId],kind:RegKind.Control,width:64,offset:0,super:Reg.None},
	{name:"ip",parts:[],kind:RegKind.Instruction,width:16,offset:0,super:Reg.Rip},
	{name:"eip",parts:[],kind:RegKind.Instruction,width:32,offset:0,super:Reg.Rip},
	{name:"rip",parts:[Reg.Ip,Reg.Rip,Reg.Eip],kind:RegKind.Instruction,width:64,offset:0,super:Reg.None},
	{name:"es",parts:[],kind:RegKind.Segment,width:16,offset:0,super:Reg.None},
	{name:"cs",parts:[],kind:RegKind.Segment,width:16,offset:0,super:Reg.None},
	{name:"ss",parts:[],kind:RegKind.Segment,width:16,offset:0,super:Reg.None},
	{name:"ds",parts:[],kind:RegKind.Segment,width:16,offset:0,super:Reg.None},
	{name:"fs",parts:[],kind:RegKind.Segment,width:16,offset:0,super:Reg.None},
	{name:"gs",parts:[],kind:RegKind.Segment,width:16,offset:0,super:Reg.None},
	{name:"cr0",parts:[],kind:RegKind.Control,width:32,offset:0,super:Reg.None},
	{name:"cr2",parts:[],kind:RegKind.Control,width:64,offset:0,super:Reg.None},
	{name:"cr3",parts:[],kind:RegKind.Control,width:64,offset:0,super:Reg.None},
	{name:"cr4",parts:[],kind:RegKind.Control,width:32,offset:0,super:Reg.None},
	{name:"cr8",parts:[],kind:RegKind.Control,width:8,offset:0,super:Reg.None},
	{name:"dr0",parts:[],kind:RegKind.Control,width:64,offset:0,super:Reg.None},
	{name:"dr1",parts:[],kind:RegKind.Control,width:64,offset:0,super:Reg.None},
	{name:"dr2",parts:[],kind:RegKind.Control,width:64,offset:0,super:Reg.None},
	{name:"dr3",parts:[],kind:RegKind.Control,width:64,offset:0,super:Reg.None},
	{name:"dr4",parts:[],kind:RegKind.Control,width:32,offset:0,super:Reg.None},
	{name:"dr5",parts:[],kind:RegKind.Control,width:32,offset:0,super:Reg.None},
	{name:"dr6",parts:[],kind:RegKind.Control,width:32,offset:0,super:Reg.None},
	{name:"dr7",parts:[],kind:RegKind.Control,width:32,offset:0,super:Reg.None},
	{name:"flag_cf",parts:[],kind:RegKind.Flag,width:1,offset:0,super:Reg.Rflags},
	{name:"flag_pf",parts:[],kind:RegKind.Flag,width:1,offset:2,super:Reg.Rflags},
	{name:"flag_af",parts:[],kind:RegKind.Flag,width:1,offset:4,super:Reg.Rflags},
	{name:"flag_zf",parts:[],kind:RegKind.Flag,width:1,offset:6,super:Reg.Rflags},
	{name:"flag_sf",parts:[],kind:RegKind.Flag,width:1,offset:7,super:Reg.Rflags},
	{name:"flag_tf",parts:[],kind:RegKind.Flag,width:1,offset:8,super:Reg.Rflags},
	{name:"flag_if",parts:[],kind:RegKind.Flag,width:1,offset:9,super:Reg.Rflags},
	{name:"flag_df",parts:[],kind:RegKind.Flag,width:1,offset:10,super:Reg.Rflags},
	{name:"flag_of",parts:[],kind:RegKind.Flag,width:1,offset:11,super:Reg.Rflags},
	{name:"flag_iopl",parts:[],kind:RegKind.Control,width:2,offset:12,super:Reg.Rflags},
	{name:"flag_nt",parts:[],kind:RegKind.Flag,width:1,offset:14,super:Reg.Rflags},
	{name:"flag_rf",parts:[],kind:RegKind.Flag,width:1,offset:16,super:Reg.Rflags},
	{name:"flag_vm",parts:[],kind:RegKind.Flag,width:1,offset:17,super:Reg.Rflags},
	{name:"flag_ac",parts:[],kind:RegKind.Flag,width:1,offset:18,super:Reg.Rflags},
	{name:"flag_vif",parts:[],kind:RegKind.Flag,width:1,offset:19,super:Reg.Rflags},
	{name:"flag_vip",parts:[],kind:RegKind.Flag,width:1,offset:20,super:Reg.Rflags},
	{name:"flag_id",parts:[],kind:RegKind.Flag,width:1,offset:21,super:Reg.Rflags},
	{name:"xmm0s",parts:[],kind:RegKind.Fp32,width:32,offset:0,super:Reg.Ymm0},
	{name:"xmm1s",parts:[],kind:RegKind.Fp32,width:32,offset:0,super:Reg.Ymm1},
	{name:"xmm2s",parts:[],kind:RegKind.Fp32,width:32,offset:0,super:Reg.Ymm2},
	{name:"xmm3s",parts:[],kind:RegKind.Fp32,width:32,offset:0,super:Reg.Ymm3},
	{name:"xmm4s",parts:[],kind:RegKind.Fp32,width:32,offset:0,super:Reg.Ymm4},
	{name:"xmm5s",parts:[],kind:RegKind.Fp32,width:32,offset:0,super:Reg.Ymm5},
	{name:"xmm6s",parts:[],kind:RegKind.Fp32,width:32,offset:0,super:Reg.Ymm6},
	{name:"xmm7s",parts:[],kind:RegKind.Fp32,width:32,offset:0,super:Reg.Ymm7},
	{name:"xmm8s",parts:[],kind:RegKind.Fp32,width:32,offset:0,super:Reg.Ymm8},
	{name:"xmm9s",parts:[],kind:RegKind.Fp32,width:32,offset:0,super:Reg.Ymm9},
	{name:"xmm10s",parts:[],kind:RegKind.Fp32,width:32,offset:0,super:Reg.Ymm10},
	{name:"xmm11s",parts:[],kind:RegKind.Fp32,width:32,offset:0,super:Reg.Ymm11},
	{name:"xmm12s",parts:[],kind:RegKind.Fp32,width:32,offset:0,super:Reg.Ymm12},
	{name:"xmm13s",parts:[],kind:RegKind.Fp32,width:32,offset:0,super:Reg.Ymm13},
	{name:"xmm14s",parts:[],kind:RegKind.Fp32,width:32,offset:0,super:Reg.Ymm14},
	{name:"xmm15s",parts:[],kind:RegKind.Fp32,width:32,offset:0,super:Reg.Ymm15},
	{name:"xmm0d",parts:[],kind:RegKind.Fp64,width:64,offset:0,super:Reg.Ymm0},
	{name:"xmm1d",parts:[],kind:RegKind.Fp64,width:64,offset:0,super:Reg.Ymm1},
	{name:"xmm2d",parts:[],kind:RegKind.Fp64,width:64,offset:0,super:Reg.Ymm2},
	{name:"xmm3d",parts:[],kind:RegKind.Fp64,width:64,offset:0,super:Reg.Ymm3},
	{name:"xmm4d",parts:[],kind:RegKind.Fp64,width:64,offset:0,super:Reg.Ymm4},
	{name:"xmm5d",parts:[],kind:RegKind.Fp64,width:64,offset:0,super:Reg.Ymm5},
	{name:"xmm6d",parts:[],kind:RegKind.Fp64,width:64,offset:0,super:Reg.Ymm6},
	{name:"xmm7d",parts:[],kind:RegKind.Fp64,width:64,offset:0,super:Reg.Ymm7},
	{name:"xmm8d",parts:[],kind:RegKind.Fp64,width:64,offset:0,super:Reg.Ymm8},
	{name:"xmm9d",parts:[],kind:RegKind.Fp64,width:64,offset:0,super:Reg.Ymm9},
	{name:"xmm10d",parts:[],kind:RegKind.Fp64,width:64,offset:0,super:Reg.Ymm10},
	{name:"xmm11d",parts:[],kind:RegKind.Fp64,width:64,offset:0,super:Reg.Ymm11},
	{name:"xmm12d",parts:[],kind:RegKind.Fp64,width:64,offset:0,super:Reg.Ymm12},
	{name:"xmm13d",parts:[],kind:RegKind.Fp64,width:64,offset:0,super:Reg.Ymm13},
	{name:"xmm14d",parts:[],kind:RegKind.Fp64,width:64,offset:0,super:Reg.Ymm14},
	{name:"xmm15d",parts:[],kind:RegKind.Fp64,width:64,offset:0,super:Reg.Ymm15},
	{name:"xmm0",parts:[],kind:RegKind.Simd128,width:128,offset:0,super:Reg.Ymm0},
	{name:"xmm1",parts:[],kind:RegKind.Simd128,width:128,offset:0,super:Reg.Ymm1},
	{name:"xmm2",parts:[],kind:RegKind.Simd128,width:128,offset:0,super:Reg.Ymm2},
	{name:"xmm3",parts:[],kind:RegKind.Simd128,width:128,offset:0,super:Reg.Ymm3},
	{name:"xmm4",parts:[],kind:RegKind.Simd128,width:128,offset:0,super:Reg.Ymm4},
	{name:"xmm5",parts:[],kind:RegKind.Simd128,width:128,offset:0,super:Reg.Ymm5},
	{name:"xmm6",parts:[],kind:RegKind.Simd128,width:128,offset:0,super:Reg.Ymm6},
	{name:"xmm7",parts:[],kind:RegKind.Simd128,width:128,offset:0,super:Reg.Ymm7},
	{name:"xmm8",parts:[],kind:RegKind.Simd128,width:128,offset:0,super:Reg.Ymm8},
	{name:"xmm9",parts:[],kind:RegKind.Simd128,width:128,offset:0,super:Reg.Ymm9},
	{name:"xmm10",parts:[],kind:RegKind.Simd128,width:128,offset:0,super:Reg.Ymm10},
	{name:"xmm11",parts:[],kind:RegKind.Simd128,width:128,offset:0,super:Reg.Ymm11},
	{name:"xmm12",parts:[],kind:RegKind.Simd128,width:128,offset:0,super:Reg.Ymm12},
	{name:"xmm13",parts:[],kind:RegKind.Simd128,width:128,offset:0,super:Reg.Ymm13},
	{name:"xmm14",parts:[],kind:RegKind.Simd128,width:128,offset:0,super:Reg.Ymm14},
	{name:"xmm15",parts:[],kind:RegKind.Simd128,width:128,offset:0,super:Reg.Ymm15},
	{name:"ymm0",parts:[Reg.Xmm0s,Reg.Ymm0,Reg.Xmm0d,Reg.Xmm0],kind:RegKind.Simd256,width:256,offset:0,super:Reg.None},
	{name:"ymm1",parts:[Reg.Xmm1s,Reg.Ymm1,Reg.Xmm1d,Reg.Xmm1],kind:RegKind.Simd256,width:256,offset:0,super:Reg.None},
	{name:"ymm2",parts:[Reg.Xmm2s,Reg.Ymm2,Reg.Xmm2d,Reg.Xmm2],kind:RegKind.Simd256,width:256,offset:0,super:Reg.None},
	{name:"ymm3",parts:[Reg.Xmm3s,Reg.Ymm3,Reg.Xmm3d,Reg.Xmm3],kind:RegKind.Simd256,width:256,offset:0,super:Reg.None},
	{name:"ymm4",parts:[Reg.Xmm4s,Reg.Ymm4,Reg.Xmm4d,Reg.Xmm4],kind:RegKind.Simd256,width:256,offset:0,super:Reg.None},
	{name:"ymm5",parts:[Reg.Xmm5s,Reg.Ymm5,Reg.Xmm5d,Reg.Xmm5],kind:RegKind.Simd256,width:256,offset:0,super:Reg.None},
	{name:"ymm6",parts:[Reg.Xmm6s,Reg.Ymm6,Reg.Xmm6d,Reg.Xmm6],kind:RegKind.Simd256,width:256,offset:0,super:Reg.None},
	{name:"ymm7",parts:[Reg.Xmm7s,Reg.Ymm7,Reg.Xmm7d,Reg.Xmm7],kind:RegKind.Simd256,width:256,offset:0,super:Reg.None},
	{name:"ymm8",parts:[Reg.Xmm8s,Reg.Ymm8,Reg.Xmm8d,Reg.Xmm8],kind:RegKind.Simd256,width:256,offset:0,super:Reg.None},
	{name:"ymm9",parts:[Reg.Xmm9s,Reg.Ymm9,Reg.Xmm9d,Reg.Xmm9],kind:RegKind.Simd256,width:256,offset:0,super:Reg.None},
	{name:"ymm10",parts:[Reg.Xmm10s,Reg.Ymm10,Reg.Xmm10d,Reg.Xmm10],kind:RegKind.Simd256,width:256,offset:0,super:Reg.None},
	{name:"ymm11",parts:[Reg.Xmm11s,Reg.Ymm11,Reg.Xmm11d,Reg.Xmm11],kind:RegKind.Simd256,width:256,offset:0,super:Reg.None},
	{name:"ymm12",parts:[Reg.Xmm12s,Reg.Ymm12,Reg.Xmm12d,Reg.Xmm12],kind:RegKind.Simd256,width:256,offset:0,super:Reg.None},
	{name:"ymm13",parts:[Reg.Xmm13s,Reg.Ymm13,Reg.Xmm13d,Reg.Xmm13],kind:RegKind.Simd256,width:256,offset:0,super:Reg.None},
	{name:"ymm14",parts:[Reg.Xmm14s,Reg.Ymm14,Reg.Xmm14d,Reg.Xmm14],kind:RegKind.Simd256,width:256,offset:0,super:Reg.None},
	{name:"ymm15",parts:[Reg.Xmm15s,Reg.Ymm15,Reg.Xmm15d,Reg.Xmm15],kind:RegKind.Simd256,width:256,offset:0,super:Reg.None},
]
// prettier-ignore
export namespace Reg {
    export function reflect(i:Reg) : RegDesc { return Reg_DescTable[i]; }
    export function toString(i:Reg) : string { return Reg_DescTable[i].name; }
}
