name: CMake

on: [push, pull_request]

jobs:
  build:
    # Skip building pull requests from the same repository
    if: ${{ github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name != github.repository) }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        target:
          - ubuntu
          - windows
          - macos
        include:
          - target: ubuntu
            os: ubuntu-latest
            build-type: Release
            extra-cmake-flags: "-DCMAKE_CXX_FLAGS=\"-flto -Wno-attributes -msse4.2\""
          - target: windows
            os: windows-latest
            build-type: Release
            extra-cmake-flags:
          - target: macos
            os: macOS-latest
            build-type: Release
            extra-cmake-flags: "-DCMAKE_CXX_FLAGS=\"-Wno-attributes -msse4.2\""
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: 'recursive'
        
    - name: Setup python
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - run: python scripts/tablegen.py .
        
    - name: Install ninja-build tool
      uses: seanmiddleditch/gha-setup-ninja@v3

    - name: Enable Developer Command Prompt
      if: ${{ runner.os == 'Windows' }}
      uses: ilammy/msvc-dev-cmd@v1.7.0

    - name: Set up GCC
      if: ${{ runner.os == 'Linux' }}
      uses: egor-tensin/setup-gcc@v1
      with:
        version: 11

    - name: Build
      run: |
        cmake -B build -G Ninja -DCMAKE_BUILD_TYPE=${{ matrix.build-type }} ${{ matrix.extra-cmake-flags }}
        cmake --build build --config ${{ matrix.build-type }} --parallel
        cmake --install build --prefix build/install --config ${{ matrix.build-type }}
